services:
  database:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin1234
      - MONGO_INITDB_DATABASE=simplecrud
    ports:
      - "27017:27017"
    command: mongod --quiet --logpath /dev/null
    logging:
      driver: "none"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://admin:admin1234@database:27017/simplecrud?authSource=admin